### PR TITLE
Turn off text selection for the polycule graph. This was causing weir…

### PR DESCRIPTION
**Pull request by darkone238**
…d behavior when editing

Tested on Edge, IE, Chrome, and Firefox. Test suite passes locally.

### CODE REVIEW

**Comment by makyo** [comment]
Oh, good catch! Would you mind maybe implementing that here? https://github.com/makyo/polycul.es/blob/master/static/style.css#L113

**Comment by darkone238** [comment]
Sounds good. I'll push a new revision later today when I have some time

**Comment by makyo** [comment]
Sweet, +1. Will deploy soon!

**Comment by darkone238** [comment]
Thank you!

**Pull request merged**
